#dockerid：https://hub.docker.com/の自分DockerId(ログインID)で切り替えください
version: '2'
services:
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ./sql/config/:/etc/mysql/conf.d
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_ROOT_PASSWORD: hoge
    app:
        image: kadai/teamlab-spring-boot-docker
        depends_on: 
            - db
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        command: sh ./startup.sh db docker docker
        environment:
            spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
            SPRING_DATASOURCE_URL: "jdbc:mysql://db/mydb"
            spring.datasource.username: "docker"
            spring.datasource.password: "docker"

